version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: camagru_web
    volumes:
      - ./src:/var/www/html:z
    ports:
      - "8080:80"
    networks:
      - camagru_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: camagru_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - camagru_network

volumes:
  db_data:

networks:
  camagru_network:
